### ISSUE TITLE
only certain pages

### ISSUE THREAD

**Issue by rowbot1** [openai/openai-cookbook#139]
Is there a way to get the web-crawl-q-and-a to only focus on a few pages of the website rather than indexing the whole site?
thanks

**Comment by logankilpatrick** [comment]
Hey @rowbot1! The short answer is yes, you can do this by adding some additional logic to the crawler code. You can also manually delete the pages which are no of interest after your site has been crawled depending on how many there are. Since this isn't an OpenAI specific question, I am going to close this for now, but also worth looking into Scrapy as a tool to help with this. Good luck!
