### ISSUE TITLE
KeyError: 'Could not automatically map gpt-4 to a tokeniser.

### ISSUE THREAD

**Issue by justanotherlad** [openai/openai-cookbook#405]
**File name**
[Question_answering_using_embeddings.ipynb](https://github.com/openai/openai-cookbook/blob/main/examples/Question_answering_using_embeddings.ipynb)

**Problem**
Using the `ask()` function with `model="gpt-4"` throws `KeyError`

**Message**
`KeyError: 'Could not automatically map gpt-4 to a tokeniser. Please use "tiktok.get_encoding" to explicitly get the tokeniser you expect.'`

**Screenshots**
![Screenshot from 2023-05-09 15-33-04](https://github.com/openai/openai-cookbook/assets/31207633/25f7552e-d9b6-41c3-88e1-bfa79948eff9)

**Comment by justanotherlad** [comment]
I was initially using `tiktoken Version: 0.3.0`, so replacing `encoding = tiktoken.encoding_for_model("gpt-4")` in `num_tokens()` method in the *Ask* section with `encoding = tiktoken.get_encoding("cl100k_base")` had solved the issue.
Later I realised the problem was with `tiktoken/model.py` script in my local machine not being able to fetch anything for `encoding_for_model("gpt-4")` that was creating the problem, so updating tiktoken to `Version: 0.4.0` (released 2 days ago) has now solved the issue, and the original code now works as expected.

**Comment by dozsa** [comment]
Using tiktoken-0.4.0 and I still see the same issue.

**Comment by justanotherlad** [comment]
@dozsa Is the bug still reproducible?

**Comment by dozsa** [comment]
@justanotherlad I still get the same error (using Azure OpenAI). Works fine with the suggested change to `tiktoken.get_encoding("cl100k_base")`.

**Comment by justanotherlad** [comment]
@dozsa Can you check if there's a conflict in your `tiktoken` version? I think your code is still using `tiktoken Version: 0.3.0`.

**Comment by ted-at-openai** [comment]
Can you share your code that isn't working?

**Comment by dozsa** [comment]
> dozsa, can you share your code that isn't working?

So the main problem is I had to change the top level variable GPT_MODEL from "gpt-3.5-turbo" to whatever I called my model deployment in Azure, as the Azure OpenAI API failed otherwise (seems you cannot pass on a model name to that API, as you can have multiple deployments of a single model, and instead you have to provide the deployment name). Now, of-course tiktoken cannot determine the encoding anymore. In hindsight what I should have done was to define another variable for that and use that instead of changing the GPT_MODEL. Only that a new user looking at this cookbook and trying to run against the Azure OpenAI API, getting the same error, and seeing suggestions online to change the model name to the deployment name, might do the same. In the end, user error. Thanks.

**Comment by ted-at-openai** [comment]
What are Azure model names normally called? I can update `tiktoken` to give the correct encodings for Azure model names, or at least give it better error messages.

**Comment by dozsa** [comment]
> What are Azure model names normally called? I can update `tiktoken` to give the correct encodings for Azure model names, or at least give it better error messages.

It is not a model name per se. It is an instance name of a model. So, in Azure OpenAI you have models, the ones we know from OpenAI. And you deploy instances of each model you need. The deployment name is just a user chosen name. And you need to use the deployment name in the API, instead of the generic model name. So, not sure what the library can do, as that can be literally any string.

**Comment by ted-at-openai** [comment]
Gotcha, thank you. I will at least update `tiktoken` to handle "gpt-35-turbo". Otherwise it sounds like it's best to grab the encoding manually, rather than by  model name.

**Comment by Eizazaitun** [comment]
Pada Jum, 26 Mei 2023, 4:40 PTG Swastik Banerjee ***@***.***>
menulis:

**Comment by vanHuong0202** [comment]
Hi guys, i am using gemini AI, but seem like the Token Counting Handler of llamaindex can not run with Gemini to do counting, have any solution for this?
