### ISSUE TITLE
[FEATURE] Add pgvector to OpenAI Docs

### ISSUE THREAD

**Issue by MentalGear** [openai/openai-cookbook#434]
(pgvector)[https://github.com/pgvector/pgvector] is a great open-source vector DB add-on for postgres. Since many dbs already use postgres, it's a great way to expand their featureset. I was a bit surprised to not find it yet on the list of open AI's recommended vector dbs and would like to see this fixed.

**Comment by Faisal1809** [comment]
I am a visually impaired user (blind), and my main purpose of using ChatGPT software is to explore the prospects of the software in visual assistance. This software is very important to me, it helps me understand the information I want to know in an unprecedented way. For example, in the process of programming, I often encounter places that I don't understand or make mistakes. Due to my visual impairment, it is relatively inefficient for me to find answers through search engines, and some content is presented in the form of pictures. However, ChatGPT interacts with me in a conversational way and provides me with text descriptions so that I can immediately hear the information and knowledge I need through a screen reader. This conversational interaction makes me feel very excited and satisfied. However, a few months ago I encountered some problems. I found that I could not log in and showed that I had no permission. I was very confused because in my impression, I had never done any inappropriate behavior. I hope you can understand my situation and help me solve this problem.

If you need to provide any additional information or documents, I am willing to cooperate. In addition, in future use, I will continue to use ChatGPT and API in accordance with regulations. I will abide by OpenAI's usage regulations and maintain a good network environment. Thank you for your help and look forward to your reply

**Comment by MentalGear** [comment]
Sorry to hear you're experiencing problems. This link is the right place to get in touch with their support: https://help.openai.com/en/collections/3742473-chatgpt

**Comment by ted-at-openai** [comment]
If anyone wants to add a pgvector guide, happy to accept it.

**Comment by dmagda** [comment]
@ted-at-openai I'm planning to contribute the Postgres pgvector guide and notebooks. This issue is closed as "completed". Does it mean that the guide has already been added? I cannot find it in the cookbooks.
