### ISSUE TITLE
requirements

### ISSUE THREAD

**Issue by kubasiak** [openai/openai-cookbook#57]
I am having problems starting with this repo
Is there a requirements.txt? Cant find

**Comment by ted-at-openai** [comment]
There isn't. Would adding one be helpful?

**Comment by ted-at-openai** [comment]
I'll add it to our to-do list.

**Comment by CoinCartel** [comment]
I had the same thing com up the other day, but the reverse. I realized that the example code in the opnAI tutorial uses a different io module than this one does due to the completions in sync... you use axios?

**Comment by CoinCartel** [comment]
hey i was wondering... can anyone contribute?

**Comment by ted-at-openai** [comment]
I'm going to close this because I don't think we're going to get to it, unfortunately. The number of examples are growing and I don't want people to need to install 100 different libraries if they're just interested in a single example. We have added requirements.txt files in the app examples. Best wishes.
